### ISSUE TITLE
Tiling for Level 0 Execution Time

### ISSUE THREAD

**Issue by da-nial** [Zhengyushan/tcga2tile#1]
Hi! hope you're doing well.
This is a nice repository, thanks for open-sourcing it!

However, When I used the code to generate tiles from a set of slides (specifically TCGA Lung Cancer), I noticed that for level 0, the execution takes a large amount of time -- around 4 hours per slide. I tested on different devices with different hardware specs but the execution is never lower than a few hours. Given that TCGA datasets might have a few hundred slides, this means that tiling all slides could take weeks.

I was wondering if this is normal, and whether it took the same amount of time for you too. And if you have any ideas for boosting the speed.

Thanks in advance.

**Comment by Zhengyushan** [comment]
Thanks for your question. In this code, we directly read the slide into memory and divide it into patches. I suppose your memory capacity cannot support you do that on level 0. 

We could read the slide row by row to reduce the memory cost. We will try to implement it and update the code soon.

**Comment by da-nial** [comment]
Thanks for the response!

You're right; I have limited memory (64 GB), which is not enough for many slides. but even for the ones that can fit in memory (and are patched successfully), the execution time is still close to a few hours (per slide).
Could you share approximately in your execution, how much memory the hardware had, and approximately how much it took per slide?

Also, would the memory affect the speed? I presumed that while it might prevent us from patching some slides, it wouldn't affect the execution speed.

**Comment by Zhengyushan** [comment]
If swap memory has been configured, the program will continue its execution even when it exceeds the available RAM. However, this will result in a significant decrease in processing speed.

Well, We have updated the code. Now, it is more memory-saving and faster than before.
